### ISSUE TITLE
Is there support for google drive downloads?

### ISSUE THREAD

**Issue by josh-65** [NicholasFeldman/BetterRecords#105]
Better Records: 1.6.2

I used this url witch in my browser instantly download it but when putting it in it says invalid url.
https://drive.google.com/uc?export=download&id=1SwPqy1vreQw1mhfuwBRXxeVitqyO8MI6

**Comment by NicholasFeldman** [comment]
This is not a direct link to an audio file.  
![image](https://user-images.githubusercontent.com/1383438/82384153-3e58bd00-99fd-11ea-9c06-5cf4b52df430.png)

A direct link to an audo file will have one of the following as content-type headers: `"audio/ogg", "application/ogg", "audio/mp3", "audio/mpeg", "audio/mpeg; charset=UTF-8", "application/octet-stream", "audio/wav", "audio/x-wav"`'

I don't believe google drive provides direct links, try with dropbox as described [here](https://github.com/NicholasFeldman/BetterRecords/wiki/Hosting-a-File-With-Dropbox).
