### ISSUE TITLE
[Suggestion] Play mp3, wav files over 10 MB limit

### ISSUE THREAD

**Issue by FranklinMCA** [NicholasFeldman/BetterRecords#114]
Please remove the limit of music file size, cause some 320 kbps music file bigger than 10 MB.

**Comment by NicholasFeldman** [comment]
File size is already adjustable in configuration. https://github.com/NicholasFeldman/BetterRecords/blob/a5ba832155c95b7f9337ed68221c464fd9de6615/src/main/kotlin/tech/feldman/betterrecords/ModConfig.kt#L62-L64
