### ISSUE TITLE
Record Etcher won't accept Dropbox files.

### ISSUE THREAD

**Issue by JoeJoeTV** [NicholasFeldman/BetterRecords#29]
BetterRecords: `1.5.4`  
Forge: `14.23.1.2582`

# Issue
When I try to download a song from Dropbox (and yes i replaced the 0 at the end with a 1) it just sais in the Record Etcher: 'application/binary is not supported!'. It does this with every sound file type i tried(ogg and mp3)

# Steps to Reproduce
1.Place Record Etcher.
2.Place Blank Record into Record Etcher.
3. Paste Dropbox Link to file.
4.The Error should pop upafter about a second of 'Validating...'.

Link to crash log: There are no errors in the log.

**Comment by NicholasFeldman** [comment]
Please share the Dropbox link you are trying to use

**Comment by JoeJoeTV** [comment]
Here is the link: https://www.dropbox.com/s/wx49xtw55yjmw2q/19%201980-F.ogg?dl=1

**Comment by NicholasFeldman** [comment]
Please refer to step #8 on this wiki page: https://github.com/NicholasFeldman/BetterRecords/wiki/Hosting A File With Dropbox

**Comment by JoeJoeTV** [comment]
Oh ok i didn't know that thanks anyway.
