### ISSUE TITLE
'Tuner Ready' Not able to tune.

### ISSUE THREAD

**Issue by Chara-Reborn** [NicholasFeldman/BetterRecords#30]
BetterRecords: `1.2.1`  
Forge: `10.13.4.16.14`

# Issue
When tuning a Frequency Crystal, all parts are filled out and working.
Frequency Tuner will say, "Tuner Ready!" however, the Tune button is grayed out.

# Steps to Reproduce
1. Aquire a Frequency Crystal
![image](https://user-images.githubusercontent.com/19896671/35204039-8072bec6-fef9-11e7-85a4-45729e7721ec.png)
2. Put it inside of the Frequency Tuner
![image](https://user-images.githubusercontent.com/19896671/35204019-6170ff42-fef9-11e7-9a93-6184d6e7b33a.png)
3. Fill the name of the Frequency Crystal. For my problem, "Chillhop Radio"
![image](https://user-images.githubusercontent.com/19896671/35204005-4f8f581e-fef9-11e7-89d6-962a040ddbcd.png)
4. Fill the Radio Source (URL). For my problem, "http://dir.xiph.org/listen/168480/listen.m3u"
![image](https://user-images.githubusercontent.com/19896671/35204051-92eaa776-fef9-11e7-89b1-5f910c3c2b6b.png)

Link to crash log: None.

**Comment by NicholasFeldman** [comment]
Fixed in a later version.
