### ISSUE TITLE
speaker explodes, server crash.

### ISSUE THREAD

**Issue by Sang-bin** [NicholasFeldman/BetterRecords#31]
BetterRecords: 1.5.4
Forge: 14.23.1.2587

# Issue
If speaker is broken using tnt, the server will crash.

# Steps to Reproduce
1. set speaker
2. set tnt
3. explosion tnt

Link to crash log: https://pastebin.com/rqWdDmrM

**Comment by NicholasFeldman** [comment]
Fixed in 1.5.5, which has been released
