### ISSUE TITLE
Now Playing bug

### ISSUE THREAD

**Issue by JoeJoeTV** [NicholasFeldman/BetterRecords#33]
BetterRecords: `1.5.5`  
Forge: `1.12.2 - 14.23.2.2616`

# Issue
I had a strange bug where it woudn't show the Now Playing message correctly when i used a cutom song. The song played but the message just said: `betterrecords.overlay.playing`

# Steps to Reproduce
1.Download song with this link: `https://dl.dropboxusercontent.com/s/wx49xtw55yjmw2q/19%201980-F.ogg?dl=1` and i named it `sas`
2.Play it

Image attached wich shows the bug
![2018-02-15_12 46 28](https://user-images.githubusercontent.com/34209417/36255282-a982a8ea-124e-11e8-9de7-76686f2c5ee8.png)

**Comment by JoeJoeTV** [comment]
Also i noticed that tis occured with all other songs too and sometimes the text was offset(see attached image)
![2018-02-15_12 51 22](https://user-images.githubusercontent.com/34209417/36255365-05198d36-124f-11e8-86e2-b1b4c37bd844.png)

**Comment by NicholasFeldman** [comment]
Is this with your client locale set to German? Looks like it might be based on the bottom right of your first image.

In any case, thank you for this, I plan on refactoring the methods/handlers to show these messages for the next release
