### ISSUE TITLE
Broken Track Name Overlay

### ISSUE THREAD

**Issue by anony55** [NicholasFeldman/BetterRecords#38]
BetterRecords: 1.5.5 (1.12.2)
Forge: 14.23.2.2651

# Issue
BetterRecords label overlay is both not functional and not centered.
When a record is inserted into the Record Player, the overlay appears but does not have the track name - but a line of text that says, "betterrecords.overlay.playing".

# Steps to Reproduce
1. Insert record into record player (Start song)
2. View track name overlay

# Image
![image](https://user-images.githubusercontent.com/38170702/39102879-891de97e-4675-11e8-9ba2-9c7fff0f0c79.png)

# Crash Log
Link to crash log: N/A

**Comment by NicholasFeldman** [comment]
Fixed in 94c3a821f9ef136d77fadf6b7bd9b8b3c71863e4, pending release.
