### ISSUE TITLE
Crash on radio URL validation

### ISSUE THREAD

**Issue by cheesealmighty** [NicholasFeldman/BetterRecords#40]
BetterRecords: 1.5.5
Forge: 14.23.4.2707

# Issue
Game crashes when trying to change radio crystal frequency, but not always. I was successful in making a crystal before, but it seems to be crashing with some URLs. 

# Steps to Reproduce
1.  Put crystal in
2.  Enter name
3.  Enter URL: "www.internet-radio.com/station/megatoncafe/ "
4. Game froze on validating, followed by a crash.

Link to crash log: https://paste.ubuntu.com/p/NbD7Qxqgsh/

Also, would love to know what constitutes as radio URL, exactly. Could you give an example? 

Best regards.

**Comment by NicholasFeldman** [comment]
The Radio url need to be a link to an ICY/Shoutcast stream. Usually, these will be encoded as mp3. I'll look into the crash.
