### ISSUE TITLE
Possible cross-mod error

### ISSUE THREAD

**Issue by Sunconure11** [NicholasFeldman/BetterRecords#41]
https://pastebin.com/mkXcxrYv

After updating my pack, I stumbled into this. It happened after updating Forgelin, NEAT, and JEI.

Forge version is 14.23.4.2707

Better Records version is BetterRecords-1.12.2-1.5.5

**Comment by NicholasFeldman** [comment]
Looks like an issue on Forgelin's end. Temporary solution is to keep forgelin @ v1.6.0 for now

**Comment by Sunconure11** [comment]
I'm noticing that after 1.7.2's release for Forgelin, Better Records items all vanish.

**Comment by NicholasFeldman** [comment]
I'll take a look and put out a hotfix if necessary as soon as 1.7.2 is available on Maven to build against

**Comment by NicholasFeldman** [comment]
Resolved, new version will be released shortly.
