### ISSUE TITLE
Spotify Playlists

### ISSUE THREAD

**Issue by KyanG7** [NicholasFeldman/BetterRecords#46]
Making it possible to play spotify playlists would be a really cool thing to add to this mod!

**Comment by KyanG7** [comment]
Also I don't know how to make it a suggestion so I just put it here sorry.

**Comment by NicholasFeldman** [comment]
According to https://developer.spotify.com/documentation/web-playback-sdk/, their playback SDK is JavaScript (AKA Web Browser) only, which cannot be used within a Minecraft Mod. Their music is also served via EME streams, which currently there are no easy way to play in Java. Additionally, the features needed to work the way this mod does are explicitly not supported, and even prohibited in their Terms of Service.

Thank you for the suggestion, but unfortunately there is no way this is possible.
