### ISSUE TITLE
[Bug] Can't get the correct audio file.

### ISSUE THREAD

**Issue by Yesterday17** [NicholasFeldman/BetterRecords#48]
BetterRecords: `1.12.2-1.5.6`  
Forge: `2705`

# Issue
It doesn't download the correct audio file.

# Steps to Reproduce
1. Use this audio, play the music:
http://music.163.com/song/media/outer/url?id=562592159.mp3
2. Follow the step of `1`, but use another audio below:
http://music.163.com/song/media/outer/url?id=35618530.mp3
3.  And you'll find that though the audios are exactly different, this mod produces samely and doesn't acquire a download for the second one.

Maybe it can't be reproduced due to copyright limit. If so, the link will return 404. If you want to see what had happened exactly, i can record a video and publish it to youtube. But i think my description is enough.
What's more, this link is not the true link of the music file. When it's visited, it will navigate to the true link. The true link is generated temporaily, but if you visit the link above, you'll always get the link for play.

**Comment by NicholasFeldman** [comment]
If the files had the same name, the mod will only use cached file if the files are the exact same amount of bytes from the HTTP header.

This particular issue might be an issue with the host you're using. URLs need to be a direct link to an audio file, with no redirects.

Feel free to re-open this issue if you need further help
