### ISSUE TITLE
Rendering Screen Crash When making a tuning crystal

### ISSUE THREAD

**Issue by BluePixelStarz** [NicholasFeldman/BetterRecords#51]
BetterRecords: `1.12.2-1.5.6`  
Forge: `14.23.4.2705`
(I am running foolcraft 3)
# Issue
Describe the problem here
I tried to tune in a crystal and the game crashed, Something to do with rendering screen.
# Steps to Reproduce
Tune in a crystal

Link to crash log: https://pastebin.com/mwkXi4Ri

**Comment by NicholasFeldman** [comment]
Fixed in d25987b2b6d83d733b89c82c19ab2c63542bf983
