### ISSUE TITLE
[Feature Request] Local file library

### ISSUE THREAD

**Issue by khionu** [NicholasFeldman/BetterRecords#53]
As a server host, I would like to be able to provide a library of audio, so there is a ready selection for my players to use, and so I can use files that are local to my server.

**Comment by NicholasFeldman** [comment]
I've been working on this functionality, I just need to implement one more packet to fully support it.

Should be just one more addition to this file
https://github.com/NicholasFeldman/BetterRecords/blob/62912d38fbf22ceee9e619a66a6c21c9c77332b8/src/main/kotlin/com/codingforcookies/betterrecords/library/Libraries.kt
