### ISSUE TITLE
Always getting new wires after breaking mod blocks | Longer wires distance

### ISSUE THREAD

**Issue by TheRealDadbeard** [NicholasFeldman/BetterRecords#56]
BetterRecords: `1.5.6`  
Forge: `2749`

# Issue
After breaking any connected block I get the wires back

# Steps to Reproduce
1.Connect something
2.Break block
3. Profit?

Is it possible to make the wires have a greater distance? I hav some speakers on the other side of the room but can't connect them.

**Comment by TheRealDadbeard** [comment]
just saw that It doesn't even use up any wires at all. I just can use one wire infinite times.

**Comment by MasterSloth1** [comment]
this bug is still a thing

BetterRecords: `1.12.2-1.6.1`  
Forge: `14.23.5.2775`

# Issue
duplication of speaker wire
 
# Steps to Reproduce
1. shift right click a radio shift right click a small speaker which uses the wire
2. break the speaker with a pick axe  you get two back

**Comment by otakup0pe** [comment]
hmm this occurs more often than not for me as well. might be willing to take a shot at it for 1.12

**Comment by P3rf3ctXZer0** [comment]
Thank you its actually a hug issue. Would be nice too if you simply added "Unlimited wire range or junction boxes." Would make decorating my house easier.

**Comment by otakup0pe** [comment]
Increasing the (configurable) length of wires is handled in #109
