### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Puyodead1** [NicholasFeldman/BetterRecords#63]
BetterRecords: `version`  
Forge: 10.13.4.1614

# Issue
Cannot read file for everything

# Steps to Reproduce
1. Etch song
2. Insert into player

**Comment by Puyodead1** [comment]
Seems to be just .mp3, i can use wav just fine

**Comment by NicholasFeldman** [comment]
Closing, no response. Feel free to re-open this if you are still experiencing issues, providing the necessary information

**Comment by Puyodead1** [comment]
https://s3-us-west-2.amazonaws.com/main2018/Never+Gonna+Give+You+Up+Original.mp3

Very sorry, I never got an email about the reply until now.
