### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SkellysGaming** [NicholasFeldman/BetterRecords#64]
BetterRecords: Unknown (Used with Rexxit modpack) 
Forge: Unknown (Used with Rexxit Modpack

# Issue
Error: Could not read file, when using the files that come with the mod

# Steps to Reproduce
1. Select Music in Etcher
2. Etch Record
3. Place in Record Player

Link to crash log: <Preferably Gist or Pastebin>

**Comment by NicholasFeldman** [comment]
The modpack uses version 1.2.0, which is an old version for 1.7.10 and no longer supported.
