### ISSUE TITLE
Record etching character issues

### ISSUE THREAD

**Issue by IdrisQe** [NicholasFeldman/BetterRecords#66]
BetterRecords: 1.5.7
Forge: 14.23.4.2760

# Issue
Two in one; I put in a bandcamp track link, although now I realize that probably won't work anyway because it's not a downloadable file. This made the record etcher spew some error about UTF-8 characters not being supported, despite it being just a normal `https://whatever.whatever/` link, no funny characters or anything.
Second issue is I figured maybe that it was getting upset at the slashes or something, so I decided to try using backslashes instead because who even knows? And the moment I types a \, the game crashed. Crashlog below.

# Steps to Reproduce
ISSUE 1:
1. Put record in etcher.
2. Type in, for example, `https://tiasu.bandcamp.com/track/rising/`
3. UTF-8 error message.
ISSUE 2:
1. Put record in etcher.
2. Type in whatever, then finish it with a \
3. Crash.

Link to crash log: https://pastebin.com/EHqvr55n

**Comment by NicholasFeldman** [comment]
Issue 1 is because that link is not a proper direct link to an audio file. A proper one will appear in the browser such as this one: `http://static.feldman.tech/mp3/fastcar.mp3`
