### ISSUE TITLE
Crash when use alongside Moving Light Sources.

### ISSUE THREAD

**Issue by ClockwerkKaiser** [NicholasFeldman/BetterRecords#68]
BetterRecords: `1.12.2-1.5.8`  
Forge: `14.23.5.2770`

# Issue
It seems there is an issue when both Better Records and [Moving Light Sources](https://github.com/jabelar/MovingLightSource-1.12) are in the same instance. The game won't even load. Seems to be an issue with the Strobe Light. 

I'll send the same report to the Moving Light Sources issue tracker as well. 

# Steps to Reproduce
1. Have both Better Records and Moving Light Sources in the same instance.
2. Load the game.
3. Crash.

Link to crash log: [Pastebin Link](https://pastebin.com/yvZe2Up8)

**Comment by NicholasFeldman** [comment]
jabelar/MovingLightSource-1.12#10

**Comment by NicholasFeldman** [comment]
Follow up on MovingLightSource issue
