### ISSUE TITLE
Fixed - Dropbox Changed File Name Direct Schema - Found tools to fix links.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [NicholasFeldman/BetterRecords#70]
BetterRecords: u-BetterRecords-1.12.2-1.6.1.jar
Shadowfacts' Forgelin: u-Forgelin-1.8.0.jar
Forge: 1.12.2 - 14.23.5.2775

# Issue
It is not downloading the song 
https://dl.dropboxusercontent.com/s/bv1e9fplj300ljy/%23NL - Deltarune - The Field of Hopes and Dreams Extended.mp3?dl=0

# Steps to Reproduce
1. Get in game 
2. Place and record blank record
3. Try and play record

# Config 
https://gist.github.com/P3rf3ctXZer0/0279144baa2761c54e6c22f7fb396fa6

# Modlist
https://gist.github.com/P3rf3ctXZer0/0541b3020787fdbd084082d1782e42db

# Related Issue
https://github.com/P3rf3ctXZer0/MC-ZER0PACKS/issues/18

# Screenshot
![2018-11-17 08_52_27-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/48662398-40783f00-ea47-11e8-8e21-4ede63d74deb.jpg)

**Comment by P3rf3ctXZer0** [comment]
![2018-11-17 09_04_45-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/48662462-ddd37300-ea47-11e8-81c1-7b5a83f9e5b6.jpg)

**Comment by P3rf3ctXZer0** [comment]
https://github.com/NicholasFeldman/BetterRecords/issues/71

**Comment by P3rf3ctXZer0** [comment]
@marioateru Make sure you watch for duplicate issues in the future.

**Comment by NicholasFeldman** [comment]
Thank you for the detailed report. Could you attach the log, as well as the URL you are using?

**Comment by P3rf3ctXZer0** [comment]
Somehow this works ... 
https://dl.dropboxusercontent.com/s/bv1e9fplj300ljy/%23NL%20-%20Deltarune%20-%20The%20Field%20of%20Hopes%20and%20Dreams%20Extended.mp3?dl=0

I think I figured out the issue - @.@ Dropbox <- When you follow wiki the first time - it does not tell you dropbox will not give the right type of link till you repost the link.

Maybe post a guide that does not use dropbox at all at this point.

**Comment by P3rf3ctXZer0** [comment]
So this the link that you get when create a link using guide with same song.

![2018-11-17 13_15_07-2018-11-17 13_14_13- nl - deltarune - the field of hopes and dreams extended mp3](https://user-images.githubusercontent.com/10351221/48664847-dec9cc00-ea6a-11e8-8894-4c4e1bce824d.jpg)

**Comment by P3rf3ctXZer0** [comment]
@NicholasFeldman notice spaces?

But when you repost the link every space is replaced with %20

When using the first direct link - dropbox does not give you the corrected direct link.

**Comment by P3rf3ctXZer0** [comment]
@NicholasFeldman 

Direct people to convert links here.
I found it works like a charm.
Add it to your main page.

http://www.isgoodstuff.com/dropbox/

**Comment by P3rf3ctXZer0** [comment]
![2018-11-18 11_31_14-my dropbox link converter](https://user-images.githubusercontent.com/10351221/48675954-7e4b9500-eb25-11e8-9671-e861bc71c67d.jpg)

**Comment by P3rf3ctXZer0** [comment]
![2018-11-18 11_31_50-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/48675960-94f1ec00-eb25-11e8-8692-35e6ffb94eb5.jpg)

![2018-11-18 11_31_57-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/48675962-97ecdc80-eb25-11e8-91e6-7f9bf246abff.jpg)

**Comment by P3rf3ctXZer0** [comment]
@NicholasFeldman 
This one works with one drive 
https://jl-workshop.com/Cloud-Storage-Direct-Link-Generator/

![2018-11-18 11_37_04-minecraft 1 12 2](https://user-images.githubusercontent.com/10351221/48676018-4f81ee80-eb26-11e8-8cf5-974743ae3492.jpg)

![2018-11-18 11_37_31-cloud drive direct link generator_drop box google drive mediafire one drive pclo](https://user-images.githubusercontent.com/10351221/48676028-5e68a100-eb26-11e8-8425-f235c047949b.jpg)

**Comment by P3rf3ctXZer0** [comment]
This is #NL-L-Youtube Poop - Adventures of Sonic The Hedgehog - Ill Find a Way.mp3

https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBdTVGVlZaWW84RnlnU1k5U212b2lfUkxmRHRY/root/content
