### ISSUE TITLE
game crash on startup

### ISSUE THREAD

**Issue by thrillking** [NicholasFeldman/BetterRecords#74]
BetterRecords: `1.5.7`  
Forge: `14.23.4`

# Issue
crashes game on startup

# Steps to Reproduce
1. start up game
2.
3. 

Link to crash log: <Preferably Gist or Pastebin> 
https://paste.dimdev.org/fuyofazogi.mccrash

**Comment by thrillking** [comment]
update: tryed with the most recent version of mod, stil crashes

https://paste.dimdev.org/inexutumoz.mccrash

**Comment by NicholasFeldman** [comment]
1.12.2 is no longer being developed for, crash logs expired.
