### ISSUE TITLE
Any URL is invalid in Record Etcher

### ISSUE THREAD

**Issue by JoeJoeTV** [NicholasFeldman/BetterRecords#83]
BetterRecords: `1.6.1`  
Forge: `14.23.5.2780`

# Issue
When I try to put any link to an mp3 file in a record etcher it says `Invalid URL`.
I tried it with Dropbox, MEGA, Google Drive and as a Discord Attachment and it still always showed up as `Invalid URL´.
I have tested it whitout any other mods and it still didn't work.

Then im tested it with an ogg file and it only worked with dropbox.

Here are my dl links

Google Drive: https://drive.google.com/uc?id=1tYtksjI-jUgp0ygH8rl0bOBRNM6foiNH
Discord: https://cdn.discordapp.com/attachments/530686108091285505/534058587396243481/cat.ogg

# Steps to Reproduce
1.Place Blank Record in Record Etcher
2.Put URL and name in the fields
3. It doesn't work

Link to crash log: No crash log

**Comment by P3rf3ctXZer0** [comment]
Can you please show me your link?

**Comment by JoeJoeTV** [comment]
Well i put my links to a ogg file in the original comment.

**Comment by JoeJoeTV** [comment]
Is there a way of fixing this, or am I doing something wrong?

**Comment by NicholasFeldman** [comment]
Your issue title is a bit misleading, considering you did get it to work with dropbox. It is expected that the discord CDN will not work, since it uses cloudflare and prevents downloads from scripts. The google drive link is also not a direct link to a file, but rather is a 302 (temporary) redirect.

BetterRecords only supports direct download links to files at the moment, and if you don't want to use DropBox they can be hosted on a self-hosted webserver.

Attached below are the HTTP Response headers from each of the url's to show my point, and in case they change in the future after this response.

If you have any more questions, feel free to respond to this issue and I'll help you as best I can, but I'm closing this since it's not an actual issue with the mod.

```
nick@Jenna:~> curl -I https://dl.dropboxusercontent.com/s/kqut4quua4eax7m/cat.ogg?dl=0
HTTP/1.1 200 OK
Server: nginx
Date: Sat, 19 Jan 2019 18:41:07 GMT
Content-Type: audio/ogg
Content-Length: 1286636
Connection: keep-alive
content-disposition: inline; filename="cat.ogg"; filename*=UTF-8''cat.ogg
x-content-type-options: nosniff
set-cookie: uc_session=3tq2rNNmC0WwMheo0HlFojjRuGIFS5HdBEbEVVFUUSeQPHZME3TsZST9NUgeJFRU; Domain=dropboxusercontent.com; httponly; Path=/; secure
accept-ranges: bytes
content-security-policy: sandbox allow-forms allow-scripts allow-top-navigation allow-popups ; report-uri https://www.dropbox.com/csp_log?policy_name=blockserver-usercontent
content-security-policy: form-action 'none' ; report-uri https://www.dropbox.com/csp_log?policy_name=blockserver-noscript ; script-src 'none'
etag: 240n
x-dropbox-request-id: e75aa594e40c7ac916249c0b25f43c6d
pragma: public
cache-control: max-age=60
X-Server-Response-Time: 456
X-Robots-Tag: noindex, nofollow, noimageindex
Strict-Transport-Security: max-age=15552000; includeSubDomains

nick@Jenna:~> curl -I https://cdn.discordapp.com/attachments/530686108091285505/534058587396243481/cat.ogg
HTTP/1.1 200 OK
Date: Sat, 19 Jan 2019 18:41:17 GMT
Content-Type: audio/ogg
Content-Length: 1286636
Connection: keep-alive
Set-Cookie: __cfduid=d57ece7eef677e920a0b7c7f54fd540151547923277; expires=Sun, 19-Jan-20 18:41:17 GMT; path=/; domain=.discordapp.com; HttpOnly
X-GUploader-UploadID: AEnB2Uqk5HhJNOU2ld0T8Bmbjr4AMC5PCbgwsKshk-Ikz4m5Zh5Wasn7fXTkM1M08MwWB5QDgKwLBqNhNT4gOBpXR1M0xXouhg
Cache-Control: public, max-age=31536000
Expires: Sun, 19 Jan 2020 18:41:17 GMT
Last-Modified: Sun, 13 Jan 2019 17:18:09 GMT
ETag: "968cde0f808270ba4c96e9d35c99cd17"
x-goog-generation: 1547399889652672
x-goog-metageneration: 1
x-goog-stored-content-encoding: identity
x-goog-stored-content-length: 1286636
Content-Disposition: attachment;%20filename=cat.ogg
x-goog-hash: crc32c=TRMRHQ==
x-goog-hash: md5=lozeD4CCcLpMlunTXJnNFw==
x-goog-storage-class: STANDARD
Alt-Svc: quic=":443"; ma=2592000; v="44,43,39,35"
CF-Cache-Status: MISS
Accept-Ranges: bytes
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
X-Robots-Tag: noindex, nofollow, noarchive, nocache, noimageindex, noodp
Server: cloudflare
CF-RAY: 49bb6f432a8791e8-EWR

nick@Jenna:~> curl -I https://drive.google.com/uc?id=1tYtksjI-jUgp0ygH8rl0bOBRNM6foiNH
HTTP/1.1 302 Moved Temporarily
Content-Type: text/html; charset=UTF-8
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: Mon, 01 Jan 1990 00:00:00 GMT
Date: Sat, 19 Jan 2019 18:41:30 GMT
Location: https://doc-14-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/qltoutfoo1viu6f31qdnvtm0tr27d2mk/1547920800000/05363172894336387376/*/1tYtksjI-jUgp0ygH8rl0bOBRNM6foiNH
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Content-Security-Policy: script-src 'nonce-STJNt6kZNVBYLn99pJDHDA' 'unsafe-inline' 'strict-dynamic' https: http: 'unsafe-eval';object-src 'none';base-uri 'self';report-uri https://csp.withgoogle.com/csp/drive-explorer/
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Server: GSE
Set-Cookie: NID=156=LbPhPbLQeHFgAqGdz33ugO5OyC7xzQKVw7u6Q5-fXewsNo-Ylr2LBBcBSTZLWDNF1X7bspAUo4V6fQnOa6sF6QRReIbWMk5w_BqEW2pK0tb53VsqXMD3Fp9mtd95z9BezsKfNCHJqelRztd6uNLElTViiW35Lfp_dDCqZj7SVOo;Domain=.google.com;Path=/;Expires=Sun, 21-Jul-2019 18:41:30 GMT;HttpOnly
Set-Cookie: NID=156=LRL1wzZGTP2zDNCDO_HVyDL65BiMWOCUTTY4Uvdo52BKWKKyHZt8G3by9jfQVnK33OliZk_4zReE90-hrQGZe8eLsVcGWefuOfHyYkpyIeCUFZYSxVtnNddQgAqBnK944AuxHR9XFpHVdOBqcw73QgOrnnfc8ydkgDa7NG1FaGQ;Domain=.google.com;Path=/;Expires=Sun, 21-Jul-2019 18:41:30 GMT;HttpOnly
Transfer-Encoding: chunked
Alt-Svc: quic=":443"; ma=2592000; v="44,43,39,35"
Accept-Ranges: none
Vary: Accept-Encoding
```

**Comment by JoeJoeTV** [comment]
No, my real problem is, that only ogg files worked with dropbox and i wanted to use mp3 files.

Here's a link to a mp3 file hosted on my dropbox:
https://dl.dropboxusercontent.com/s/cf5z1888mzr3o5y/Dunderpatrullen%20-%20Pixie%20Trust.mp3?dl=0
(If I try it with curl on the rootserver, where i host my minecraft server I get a 301 error, but on my pc not)

And is there any way to get direct links from google drive or mega or somethin other than dropbox.

And I have a rootserver, where I could host files, but i never really set up any web server and I don't have a domain.

**Comment by NicholasFeldman** [comment]
Odd, everything is working with that link for me. Try this one and let me know if it works: http://static.feldman.tech/mp3/fastcar.mp3

As far as I know and have tested, there is no way to get direct links from google drive or mega.

**Comment by JoeJoeTV** [comment]
I don't know how, but I got my mp3 linka and your link to work.
I need to test other files, but i think it works now.
