### ISSUE TITLE
Radio URL's

### ISSUE THREAD

**Issue by Draylynn** [NicholasFeldman/BetterRecords#84]
BetterRecords: `1.12.2-1.6.1`  
Forge: `14.23.5.2811`

# Issue
Not for the want of trying, but, I can't seem to get a single URL to work with radios. ICY or otherwise, the URL's always end up either;
a) Not being able to scribe to the crystal.
b) Silently error'ing away: java.io.IOException: mark/reset not supported
I'm not sure if it's an FML build incompatibility or user error; Do you have a URL I can test, that is suppose to 100% work?

(Note: Xatworld/tunein guide doesn't work, 404's, site errors all over no "streamurls" or direct URL's in the source etc).

**Comment by LegalizeLolis** [comment]
Hi Draylynn, I'm ashamed that this is the only medium I could find of yours(For me, not you of course. I mean no disrespect) but I was one of the people that got banned today in the MineTogether chat, and was hoping we could talk this through if you're willing to consider. My Discord is Forgotten Failure#7700 and I will await your message. Thanks in advance!

**Comment by Draylynn** [comment]
Yeh... @LegalizeLolis this isn't the place to contact me, MineTogether has it's own Github, very inappropriate for you to do this, stick with your issue on MT.

**Comment by dabluecaboose** [comment]
I am also having considerable issues getting the internet radio working, I cannot seem to find a working URL anywhere that even is valid for the tuner.  I have no problems with using dropbox-hosted URLs, though, thanks to the guide on the mod page.  Perhaps a simple guide for acquiring the appropriate URL format would help?

**Comment by Mamumimi** [comment]
nothing in here http://provisioning.streamtheworld.com/m3u/WMMRFMAACIHR.m3u
not this https://17413.live.streamtheworld.com/WMMRFMAACIHR.aac
nothing on this site seems to work http://dir.xiph.org/

**Comment by Toricima** [comment]
Try with the latest version, that was released yesterday. There was an issue with some older SHOUTcast servers being incompatible, but that was on the side of the plugin (too strict in casing).

**Comment by NicholasFeldman** [comment]
Closing because this is stale and probably fixed, reopen if it isn't
