### ISSUE TITLE
Can't click the tune button when url valid (button changes, but unclickable)

### ISSUE THREAD

**Issue by KILLAKAN10** [NicholasFeldman/BetterRecords#96]
BetterRecords: `1.6.1 (1.12.2)`  
Forge: `14.23.5.2487`

# Issue
It's, weird, the button doesn't remain greyed out, it changes, but it's unclickable

# Steps to Reproduce
1. Find a url (http://stream.lesonparisien.com/mid.ogg)
2. Fill in the name and url
3. Be unable to actually click the button, despite looking completely fine.
4. ?????
5. Be very confused and come here.

Log: None, there's no anomalies or crashes that really show up

**Comment by NicholasFeldman** [comment]
Unable to reproduce
