### ISSUE TITLE
Build problems

### ISSUE THREAD

**Issue by EnterFor** [NicholasFeldman/BetterRecords#97]
Hello, curseforge was released in 2018
There are modified records on github
Can I build and use it by myself?
I really like this Mod, I hope you can reply to me
Sorry, my English is poor. I'm Chinese
Thank you very much!

**Comment by EnterFor** [comment]
What's the difference between curseforge's version and github's?

**Comment by diamondo25** [comment]
Better Records on Cursforge is the same as this repo

**Comment by NicholasFeldman** [comment]
Yes, you can always build from source yourself. Be aware though that anything on the master branch is already released on curse.
